/* This file is automatically generated by configure */
/* DO NOT EDIT MANUALLY */

#ifndef CONFIG_H
#define CONFIG_H


#define SCUMM_LITTLE_ENDIAN
/* #define SCUMM_BIG_ENDIAN */
//#define HAVE_X86
#define SCUMM_NEED_ALIGNMENT
/* #define USE_NASM */

/* Data types */
typedef unsigned char byte;
typedef unsigned int uint;
typedef unsigned char uint8;
typedef unsigned short uint16;
typedef unsigned int uint32;
typedef signed char int8;
typedef signed short int16;
typedef signed int int32;

/* Libs */
#undef USE_VORBIS
#define USE_TREMOR
#undef USE_FLAC
#undef USE_MAD
#undef USE_ALSA
#define USE_ZLIB
#undef USE_MPEG2
#undef USE_FLUIDSYNTH
#undef USE_READLINE
//#define USE_MT32EMU
//#define USE_INDEO3

/* Options */
#undef USE_TEXT_CONSOLE
#undef USE_MT32EMU
#define USE_INDEO3
#define USE_RGB_COLOR

/* Plugin settings */
/* -> plugins disabled */

#endif /* CONFIG_H */
